<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypingGameSeeder extends Seeder
{
    public function run(): void
    {
        $sentences = [
            "The quick brown fox jumps over the lazy dog.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "Typing practice improves speed and accuracy.",
            "Practice makes perfect, so type every day.",
            "Keep your hands relaxed and fingers ready.",
            "Consistent practice helps you type faster.",
            "Accuracy is more important than speed at first.",
            "Focus on proper finger placement when typing.",
            "Short paragraphs help beginners improve quickly.",
            "Long paragraphs challenge your endurance and skill.",
            "The sun rises in the east and sets in the west.",
            "A quick brown fox jumps over the lazy dog.",
            "Typing every day can significantly improve your speed.",
            "Reading books helps expand your knowledge and imagination.",
            "She always drinks a cup of coffee in the morning.",
            "The rain fell softly over the quiet village.",
            "Learning a new language opens doors to many cultures.",
            "He checked his email before leaving for work.",
            "The cat slept peacefully on the warm windowsill.",
            "Exercising regularly keeps both your body and mind healthy.",
            "The children played happily in the park after school.",
            "Cooking at home can save money and improve nutrition.",
            "The teacher explained the lesson clearly to all students.",
            "Walking in nature can reduce stress and improve mood.",
            "He wrote a letter to his friend who lives abroad.",
            "The train arrived at the station right on time.",
            "She enjoyed painting landscapes during her free time.",
            "The dog barked loudly when someone approached the house.",
            "Technology is constantly changing the way we communicate.",
            "The flowers in the garden bloomed beautifully this spring.",
            "Reading instructions carefully prevents mistakes in tasks.",
            "He enjoys jogging every morning before breakfast.",
            "The library was quiet except for the soft rustle of pages.",
            "Traveling to new places broadens your perspective.",
            "She studied hard for her final exams last semester.",
            "The baker prepared fresh bread early in the morning.",
            "Sunsets over the ocean are always breathtaking.",
            "Good time management helps increase productivity.",
            "The musician practiced the piano for several hours.",
            "Eating healthy food can improve energy levels.",
            "He repaired his bike before going for a ride.",
            "The movie captured the emotions of its characters well.",
            "Learning from mistakes is an important part of growth.",
            "She watered the plants every evening in her backyard.",
            "The children listened attentively to the storyteller.",
            "Fresh air and sunlight are essential for good health.",
            "He carefully painted the model airplane with precision.",
            "Volunteering in the community can be very rewarding.",
            "The chef prepared a delicious meal for the guests.",
            "Listening to music can help relax the mind.",
            "The bird built its nest high in the tree.",
            "Writing a journal helps organize thoughts and feelings.",
            "She knitted a warm scarf for her grandmother.",
            "The dog ran happily across the open field.",
            "He studied the stars with his telescope at night.",
            "The rain washed the streets clean after the storm.",
            "Playing board games is a fun way to spend time with family.",
            "The clock struck midnight, signaling the start of a new day.",
            "He fixed the broken chair with some tools from the garage.",
            "The students participated actively in the science experiment.",
            "She enjoyed a peaceful afternoon reading by the fireplace.",
            "The morning air smelled fresh after the rain.",
            "She carefully placed the vase on the table.",
            "He enjoys reading mystery novels on weekends.",
            "The children built a sandcastle on the beach.",
            "A gentle breeze moved the leaves on the trees.",
            "He brewed a cup of tea before starting work.",
            "The painter mixed colors to create a new shade.",
            "The dog chased its tail in circles happily.",
            "She found a small, hidden path in the forest.",
            "The teacher praised the students for their hard work.",
            "He opened the window to let in the sunlight.",
            "The musician tuned his guitar before the performance.",
            "She wrote a heartfelt letter to her best friend.",
            "The chef garnished the dish with fresh herbs.",
            "The sun peeked through the clouds after the storm.",
            "He carefully folded the clothes and put them away.",
            "The baby laughed at the funny faces her father made.",
            "They walked along the riverbank enjoying the view.",
            "The scientist recorded the results in her notebook.",
            "She watered the flowers in the garden every morning.",
            "He tied his shoelaces before running in the park.",
            "The clock on the wall chimed three times.",
            "She placed a bookmark in her favorite novel.",
            "The birds sang loudly at dawn in the forest.",
            "He organized his desk to make it look tidy.",
            "The kids played hide and seek in the backyard.",
            "She painted a portrait of her grandmother.",
            "The cat stretched lazily in the afternoon sun.",
            "He packed a small bag for the weekend trip.",
            "The waves crashed gently against the shore.",
            "She cleaned the kitchen after preparing lunch.",
            "The train moved slowly through the countryside.",
            "He practiced drawing every evening for an hour.",
            "The wind rustled the pages of the open book.",
            "She smiled as she watched the sunset on the horizon.",
            "The dog wagged its tail when it saw its owner.",
            "He wrote down the recipe before starting to cook.",
            "The flowers attracted many colorful butterflies.",
            "She organized her books by color and size.",
            "The children listened to the story with excitement.",
            "He polished his shoes until they shined brightly.",
            "The river reflected the mountains in its calm water.",
            "She adjusted the curtains to block the sunlight.",
            "The car engine roared as he started the journey.",
            "He solved the puzzle in less than ten minutes.",
            "The baby slept peacefully in her crib.",
            "She practiced yoga every morning before breakfast.",
            "The lamp cast a warm glow in the room.",
            "He carefully measured the ingredients for the cake.",
            "The birds built nests in the tall trees outside."
        ];

        foreach ($sentences as $sentence) {
            DB::table('typing_games')->insert([
                'sentence' => $sentence,
                'number_of_words' => str_word_count($sentence),
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
}
